CREATE TABLE IF NOT EXISTS `USERS` (
    `ID` BINARY(16) PRIMARY KEY NOT NULL,
    `FULL_NAME` VARCHAR(150) NOT NULL,
    `LOGIN` VARCHAR(100) NOT NULL UNIQUE,
    `PASSWORD` VARCHAR(100) NOT NULL,
    `ROLE` ENUM('ADMIN') NOT NULL
);