CREATE TABLE IF NOT EXISTS `USERS` (
    `ID` BINARY(16) PRIMARY KEY NOT NULL,
    `FULL_NAME` VARCHAR(100) NOT NULL,
    `LOGIN` VARCHAR(100) NOT NULL UNIQUE,
    `PASSWORD` VARCHAR(100) NOT NULL,
    `ROLE` ENUM('ADMIN', 'USER') NOT NULL,
    `ABOUT` TEXT NOT NULL,
    `ACTIVE` TINYINT(1) NOT NULL
);