CREATE TRIGGER CHECK_LENGTH_PASSWORD_BEFORE_UPDATE
BEFORE UPDATE ON `USERS`
FOR EACH ROW
BEGIN
    IF CHAR_LENGTH(NEW.PASSWORD) < 8 THEN
        SIGNAL SQLSTATE '45004' SET MESSAGE_TEXT = 'Password must be longer than 7 characters';
    END IF;
END;